{{- if .Values.codeInterpreter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-code-interpreter
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: code-interpreter
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: code-interpreter
{{- end }}
