{{- if .Values.firecrawl.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-firecrawl
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: firecrawl
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: firecrawl
{{- end }}
