{{- if .Values.firecrawl.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-firecrawl-redis
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: firecrawl-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: firecrawl-redis
{{- end }}
