{{- if .Values.searxng.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-searxng
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
{{- end }}
